### ISSUE TITLE
I want to change the output size.

### ISSUE THREAD

**Issue by kimahiro** [happyjin/ConvGRU-pytorch#1]
Hi happyjin-san,

Hello there. I am a student from Japan. I tried using your ConvGRU-pytorch implementation.

However, I'm having trouble getting the desired output size even after trying to change the output size of the ConvGRU model. I need the final output size to be (b, t, c, h, w) = (32, 2, 1, 100, 100). Could you please guide me on how to make this modification?

Looking forward to your reply.

**Comment by happyjin** [comment]
Please refer to https://www.baeldung.com/cs/convolutional-layer-size
